debug:
	gcc -Wall -g -o ~/bin/inoswp ~/dotfile/script/c/inotify_example.c
	gdb -q -args inoswp /tmp/swp
clean:
	rm ~/bin/inoswp
inoswp:
	gcc -Wall -g -o ~/bin/inoswp ~/dotfile/script/c/inotify_example.c
