debug:
	gcc -Wall -g -o ~/bin/inoswp ~/dotfile/script/c/inotify/inotify_swp.c
	gdb -q -args inoswp /tmp/swp
clean:
	rm ~/bin/inoswp
inoswp:
	gcc -Wall -g -o ~/bin/inoswp ~/dotfile/script/c/inotify/inotify_swp.c
